
export default {
    template:`
        <section class="about-page app-main">
            <div class="about-title">Miss Book </div>
            <p>is Lorem ipsum dolor sit amet consectetur, adipisicing elit. Error, qui recusandae! Quae itaque placeat a temporibus facere vero enim qui! Eligendi dolorum debitis necessitatibus perspiciatis sed fugiat molestias maiores tempora impedit ullam atque numquam adipisci expedita unde laborum, excepturi voluptatibus accusamus dolorem quisquam asperiores minus vitae. Sed nobis accusamus eaque.</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit numquam, nemo similique dicta fugit maiores cum. Magni quae repellat facilis laudantium dolore aliquam ipsam, in sit nobis quos error doloremque corporis laboriosam nostrum quasi voluptate odit quidem vitae placeat a incidunt officia. Aspernatur tempore eaque quis quaerat recusandae, at minus!</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt cupiditate, eaque doloremque accusantium explicabo error distinctio quisquam iusto voluptates praesentium veniam provident recusandae veritatis eius minus quod voluptatibus delectus quam? Voluptatibus ullam placeat eos illo.</p>
            <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Id quaerat nobis fugit officia iure velit debitis sed maiores. Quis molestiae iure veniam error unde voluptatibus. Consectetur at voluptatibus, mollitia, sunt libero ex non in molestias dolorum dolore nobis, obcaecati cupiditate! Commodi at ex eveniet neque. Nobis impedit esse omnis deserunt. Quasi perferendis voluptatibus quidem eligendi asperiores? Molestiae laboriosam veritatis nulla placeat corporis praesentium sit ullam autem laudantium rem beatae voluptates impedit cumque labore, sunt quis quibusdam aperiam amet debitis, earum exercitationem accusantium repudiandae harum! Id recusandae debitis, perspiciatis, cupiditate vero a suscipit animi laboriosam, aspernatur quaerat at. Dignissimos, iusto incidunt quibusdam repellat obcaecati exercitationem, ut voluptatem neque similique, inventore consectetur? Numquam sit, voluptates error autem, neque excepturi modi magnam amet commodi impedit ad vel voluptatem quae quibusdam rerum delectus, voluptatum iste harum at perspiciatis reiciendis. Beatae, repellat aperiam! Id incidunt magni expedita ad illum veritatis, consequatur nemo consectetur, illo quis quidem ullam ducimus explicabo cumque mollitia vel quam sed odit minima eaque. Quam fugit ea nostrum harum, officiis quis cumque aspernatur quia praesentium dicta excepturi deleniti at animi sapiente eaque molestiae esse iusto quod. Libero saepe assumenda atque aspernatur distinctio officiis dicta nihil laborum, itaque aliquid, quam veniam voluptatum ad!</p>
            <hr>
            <div class="about-title"> About Us: </div>
             <p> Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima nihil perspiciatis nemo rerum eligendi molestiae rem, quod sed aut at laudantium aliquid? Ex, reprehenderit! Doloremque natus assumenda sequi nostrum quam!</p>
            <p> Lorem ipsum dolor sit amet consectetur adipisicing elit. Facilis modi recusandae non consequatur. Sequi dolorem ipsa nulla odio obcaecati nisi quas corrupti. Consequuntur, dolore optio? Ad, voluptatibus in vel dolor quas eligendi sunt saepe quis doloribus quia, non molestias quod consectetur voluptatum ex praesentium quam eveniet sequi? Fugit omnis vel non pariatur unde eos molestiae quasi asperiores sequi, eaque sapiente voluptates officiis harum, fugiat sit, aliquid itaque iusto voluptatem eius cupiditate ad. Alias doloribus ad harum porro eos voluptates, suscipit consequuntur pariatur dolorum illo vel eius impedit fuga assumenda ab odio quis commodi. In, aut unde praesentium debitis aliquid dignissimos?</p>
            <p> Lorem ipsum dolor sit amet consectetur adipisicing elit. Facilis modi recusandae non consequatur. Sequi dolorem ipsa nulla odio obcaecati nisi quas corrupti. Consequuntur, dolore optio? Ad, voluptatibus in vel dolor quas eligendi sunt saepe quis doloribus quia, non molestias quod consectetur voluptatum ex praesentium quam eveniet sequi? Fugit omnis vel non pariatur unde eos molestiae quasi asperiores sequi, eaque sapiente voluptates officiis harum, fugiat sit, aliquid itaque iusto voluptatem eius cupiditate ad. Alias doloribus ad harum porro eos voluptates, suscipit consequuntur pariatur dolorum illo vel eius impedit fuga assumenda ab odio quis commodi. In, aut unde praesentium debitis aliquid dignissimos?</p>


        </section>
    `,
    methods:{
        }
    }